import { Appointment } from "@/components/types/PatientDashboardTypes/OverviewPageTypes";

export const upcomingAppointments: Appointment[] = [
  {
    id: "apt-001",
    doctorName: "Dr. Sarah Ahmed",
    speciality: "Cardiology",
    date: "2026-08-27",
    time: "10:30 AM",
    status: "upcoming",
    type: "In-person",
    location: "Apollo Hospital, Dhaka",
    image: "/images/doctors/doctor-1.png",
  },
  {
    id: "apt-002",
    doctorName: "Dr. Rafiq Islam",
    speciality: "Dermatology",
    date: "2026-09-05",
    time: "02:15 PM",
    status: "upcoming",
    type: "Online",
    location: "Video Consultation",
    image: "/images/doctors/doctor-2.png",
  },
  {
    id: "apt-003",
    doctorName: "Dr. Nasreen Akter",
    speciality: "Pediatrics",
    date: "2026-09-08",
    time: "11:00 AM",
    status: "upcoming",
    type: "In-person",
    location: "Square Hospital, Dhaka",
    image: "/images/doctors/doctor-3.png",
  },
  {
    id: "apt-004",
    doctorName: "Dr. Kamal Hossain",
    speciality: "Orthopedics",
    date: "2026-09-12",
    time: "09:45 AM",
    status: "upcoming",
    type: "Online",
    location: "Video Consultation",
    image: "/images/doctors/doctor-4.png",
  },
];

export const allAppointments: Appointment[] = [
  ...upcomingAppointments,
  {
    id: "apt-005",
    doctorName: "Dr. Tanvir Rahman",
    speciality: "Neurology",
    date: "2026-08-15",
    time: "09:00 AM",
    status: "completed",
    type: "In-person",
    location: "Square Hospital, Dhaka",
    image: "/images/doctors/doctor-5.png",
  },
  {
    id: "apt-006",
    doctorName: "Dr. Fatima Begum",
    speciality: "Gynecology",
    date: "2026-08-20",
    time: "04:30 PM",
    status: "completed",
    type: "Online",
    location: "Video Consultation",
    image: "/images/doctors/doctor-6.png",
  },
  {
    id: "apt-007",
    doctorName: "Dr. Imran Hossain",
    speciality: "Orthopedics",
    date: "2026-08-10",
    time: "11:30 AM",
    status: "cancelled",
    type: "In-person",
    location: "Apollo Hospital, Dhaka",
    image: "/images/doctors/doctor-7.png",
  },
];
