const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Ahmed",
    image: "/images/doctors/doctor-1.png",
    speciality: "Cardiologist",
    degree: "MBBS, MD (Cardiology), FACC",
    rating: 4.9,
    reviewCount: 45,
    experience: 12,
    consultationFee: 1200,
    consultationType: "In-person & Online",
    chamberLocation: "Apollo Hospital, Dhaka",
    about:
      "Dr. Sarah Ahmed is a board-certified cardiologist with over 12 years of experience in diagnosing and treating cardiovascular diseases. She specializes in interventional cardiology and heart failure management.",
    education: "MBBS from Dhaka Medical College; MD (Cardiology) from BSMMU; Fellowship from American College of Cardiology",
    services: [
      "ECG & Echocardiogram",
      "Angiography",
      "Heart Failure Management",
      "Cardiac Risk Assessment",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 2,
    name: "Dr. Michael Rahman",
    image: "/images/doctors/doctor-2.png",
    speciality: "Neurologist",
    degree: "MBBS, MD (Neurology), FRCP",
    rating: 4.8,
    reviewCount: 21,
    experience: 10,
    consultationFee: 1000,
    consultationType: "In-person",
    chamberLocation: "Square Hospital, Dhaka",
    about:
      "Dr. Michael Rahman is an experienced neurologist specializing in stroke management, epilepsy, and neurodegenerative disorders. He is committed to providing comprehensive neurological care.",
    education:
      "MBBS from Chittagong Medical College; MD (Neurology) from BSMMU; FRCP from Royal College of Physicians",
    services: [
      "Stroke Treatment",
      "EEG & EMG",
      "Epilepsy Management",
      "Headache & Migraine Clinic",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 3,
    name: "Dr. Emily Wilson",
    image: "/images/doctors/doctor-3.png",
    speciality: "Dermatologist",
    degree: "MBBS, DDVL, MD (Dermatology)",
    rating: 4.7,
    reviewCount: 16,
    experience: 8,
    consultationFee: 800,
    consultationType: "Online & In-person",
    chamberLocation: "United Hospital, Dhaka",
    about:
      "Dr. Emily Wilson is a skilled dermatologist with expertise in treating skin, hair, and nail disorders. She offers both medical and cosmetic dermatology services.",
    education:
      "MBBS from Mymensingh Medical College; DDVL from IPGMER; MD (Dermatology) from BSMMU",
    services: [
      "Acne & Scar Treatment",
      "Laser Therapy",
      "Skin Allergy Testing",
      "Cosmetic Dermatology",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 4,
    name: "Dr. James Anderson",
    image: "/images/doctors/doctor-4.png",
    speciality: "Orthopedic Surgeon",
    degree: "MBBS, MS (Orthopedics), FACS",
    rating: 4.9,
    reviewCount: 71,
    experience: 15,
    consultationFee: 1500,
    consultationType: "In-person",
    chamberLocation: "Bangabandhu Sheikh Mujib Medical University Hospital, Dhaka",
    about:
      "Dr. James Anderson is a renowned orthopedic surgeon with extensive experience in joint replacement, spine surgery, and sports injury management.",
    education:
      "MBBS from Dhaka Medical College; MS (Orthopedics) from BSMMU; FACS from American College of Surgeons",
    services: [
      "Knee Replacement",
      "Hip Replacement",
      "Spine Surgery",
      "Sports Injury Management",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 5,
    name: "Dr. Olivia Martin",
    image: "/images/doctors/doctor-5.png",
    speciality: "Pediatrician",
    degree: "MBBS, DCH, FCPS (Pediatrics)",
    rating: 4.8,
    reviewCount: 24,
    experience: 9,
    consultationFee: 900,
    consultationType: "Online & In-person",
    chamberLocation: "Kidney Foundation Hospital, Dhaka",
    about:
      "Dr. Olivia Martin is a caring pediatrician dedicated to the health and well-being of children from newborns to adolescents. She specializes in growth monitoring and childhood vaccinations.",
    education:
      "MBBS from Rajshahi Medical College; DCH from IPGMER; FCPS (Pediatrics) from BCPS",
    services: [
      "Vaccination",
      "Growth Monitoring",
      "Childhood Illness Treatment",
      "Nutritional Counseling",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 6,
    name: "Dr. Daniel Karim",
    image: "/images/doctors/doctor-6.png",
    speciality: "General Physician",
    degree: "MBBS, MD (Internal Medicine)",
    rating: 4.6,
    reviewCount: 29,
    experience: 7,
    consultationFee: 600,
    consultationType: "In-person & Online",
    chamberLocation: "Popular Diagnostic Center, Dhaka",
    about:
      "Dr. Daniel Karim is a dedicated general physician providing comprehensive primary care. He focuses on preventive medicine and chronic disease management.",
    education:
      "MBBS from Sylhet MAG Osmani Medical College; MD (Internal Medicine) from BSMMU",
    services: [
      "General Checkup",
      "Diabetes Management",
      "Hypertension Care",
      "Health Screening",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 7,
    name: "Dr. Sophia Williams",
    image: "/images/doctors/doctor-7.png",
    speciality: "Gynecologist",
    degree: "MBBS, FCPS (Gynecology & Obstetrics)",
    rating: 4.9,
    reviewCount: 42,
    experience: 13,
    consultationFee: 1100,
    consultationType: "In-person",
    chamberLocation: "LABAID Hospital, Dhaka",
    about:
      "Dr. Sophia Williams is a highly experienced gynecologist specializing in high-risk pregnancies, infertility treatment, and minimally invasive gynecological surgery.",
    education:
      "MBBS from Dhaka Medical College; FCPS (Gynecology & Obstetrics) from BCPS",
    services: [
      "Prenatal Care",
      "Infertility Treatment",
      "Laparoscopic Surgery",
      "Menstrual Disorder Management",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 8,
    name: "Dr. Robert Hasan",
    image: "/images/doctors/doctor-8.png",
    speciality: "Ophthalmologist",
    degree: "MBBS, FCPS (Ophthalmology), FRCS",
    rating: 4.7,
    reviewCount: 39,
    experience: 11,
    consultationFee: 850,
    consultationType: "Online & In-person",
    chamberLocation: "Ispahani Eye Hospital, Dhaka",
    about:
      "Dr. Robert Hasan is a skilled ophthalmologist specializing in cataract surgery, glaucoma, and retinal diseases. He has performed over 5,000 successful eye surgeries.",
    education:
      "MBBS from Sir Salimullah Medical College; FCPS (Ophthalmology) from BCPS; FRCS from Royal College of Surgeons",
    services: [
      "Cataract Surgery",
      "LASIK",
      "Glaucoma Treatment",
      "Retinal Disorder Management",
    ],
    availableDays: ["Sunday", "Wednesday", "Friday"],
  },
  {
    id: 9,
    name: "Dr. Isabella Khan",
    image: "/images/doctors/doctor-9.png",
    speciality: "Psychiatrist",
    degree: "MBBS, MD (Psychiatry), MRCPsych",
    rating: 4.8,
    reviewCount: 67,
    experience: 10,
    consultationFee: 1000,
    consultationType: "Online & In-person",
    chamberLocation: "National Institute of Mental Health, Dhaka",
    about:
      "Dr. Isabella Khan is a compassionate psychiatrist with expertise in treating anxiety, depression, and mood disorders. She provides both medication management and psychotherapy.",
    education:
      "MBBS from Dhaka Medical College; MD (Psychiatry) from BSMMU; MRCPsych from Royal College of Psychiatrists",
    services: [
      "Depression Treatment",
      "Anxiety Management",
      "Cognitive Behavioral Therapy",
      "Stress Counseling",
    ],
    availableDays: ["Monday", "Thursday", "Saturday"],
  },
  {
    id: 10,
    name: "Dr. William Chowdhury",
    image: "/images/doctors/doctor-10.png",
    speciality: "ENT Specialist",
    degree: "MBBS, FCPS (ENT), DOHNS",
    rating: 4.6,
    reviewCount: 54,
    experience: 8,
    consultationFee: 750,
    consultationType: "In-person & Online",
    chamberLocation: "ENT Care Center, Dhaka",
    about:
      "Dr. William Chowdhury is an ENT specialist with a focus on sinus disorders, hearing loss, and throat conditions. He uses the latest endoscopic techniques.",
    education:
      "MBBS from Chittagong Medical College; FCPS (ENT) from BCPS; DOHNS from Royal College of Surgeons",
    services: [
      "Sinus Surgery",
      "Hearing Assessment",
      "Tonsillectomy",
      "Voice Disorder Treatment",
    ],
    availableDays: ["Tuesday", "Wednesday", "Friday"],
  },
  {
    id: 11,
    name: "Dr. Emma Hossain",
    image: "/images/doctors/doctor-11.png",
    speciality: "Endocrinologist",
    degree: "MBBS, MD (Endocrinology & Metabolism)",
    rating: 4.9,
    reviewCount: 51,
    experience: 14,
    consultationFee: 1200,
    consultationType: "In-person",
    chamberLocation: "BIRDEM Hospital, Dhaka",
    about:
      "Dr. Emma Hossain is a leading endocrinologist specializing in diabetes, thyroid disorders, and hormonal imbalances. She has published numerous research papers in her field.",
    education:
      "MBBS from Dhaka Medical College; MD (Endocrinology & Metabolism) from BSMMU",
    services: [
      "Diabetes Management",
      "Thyroid Disorder Treatment",
      "Hormone Replacement Therapy",
      "Metabolic Disorder Care",
    ],
    availableDays: ["Sunday", "Tuesday", "Saturday"],
  },
  {
    id: 12,
    name: "Dr. Alexander Islam",
    image: "/images/doctors/doctor-12.png",
    speciality: "Gastroenterologist",
    degree: "MBBS, MD (Gastroenterology), FACG",
    rating: 4.8,
    reviewCount: 88,
    experience: 12,
    consultationFee: 1300,
    consultationType: "In-person & Online",
    chamberLocation: "Digestive Disease Hospital, Dhaka",
    about:
      "Dr. Alexander Islam is an accomplished gastroenterologist with expertise in liver diseases, inflammatory bowel disease, and advanced endoscopic procedures.",
    education:
      "MBBS from Rajshahi Medical College; MD (Gastroenterology) from BSMMU; FACG from American College of Gastroenterology",
    services: [
      "Upper GI Endoscopy",
      "Colonoscopy",
      "Liver Disease Management",
      "IBD Treatment",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 13,
    name: "Dr. Fatima Rahman",
    image: "/images/doctors/doctor-1.png",
    speciality: "Cardiologist",
    degree: "MBBS, MD (Cardiology)",
    rating: 4.7,
    reviewCount: 33,
    experience: 9,
    consultationFee: 1000,
    consultationType: "Online & In-person",
    chamberLocation: "Care Hospital, Dhaka",
    about:
      "Dr. Fatima Rahman specializes in preventive cardiology and cardiac rehabilitation. She is dedicated to helping patients manage their heart health through lifestyle modifications.",
    education:
      "MBBS from Dhaka Medical College; MD (Cardiology) from BSMMU",
    services: [
      "Cardiac Rehabilitation",
      "Preventive Cardiology",
      "Holter Monitoring",
      "Stress Test",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 14,
    name: "Dr. Arif Hossain",
    image: "/images/doctors/doctor-2.png",
    speciality: "Neurologist",
    degree: "MBBS, MD (Neurology)",
    rating: 4.5,
    reviewCount: 19,
    experience: 7,
    consultationFee: 850,
    consultationType: "In-person",
    chamberLocation: "Neurology Clinic, Dhaka",
    about:
      "Dr. Arif Hossain is a neurologist with a focus on movement disorders and neurodegenerative diseases. He provides comprehensive care for patients with Parkinson's and Alzheimer's.",
    education: "MBBS from Mymensingh Medical College; MD (Neurology) from BSMMU",
    services: [
      "Parkinson's Disease Management",
      "Alzheimer's Care",
      "Nerve Conduction Study",
      "Movement Disorder Clinic",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 15,
    name: "Dr. Nusrat Jahan",
    image: "/images/doctors/doctor-3.png",
    speciality: "Dermatologist",
    degree: "MBBS, MD (Dermatology)",
    rating: 4.8,
    reviewCount: 56,
    experience: 11,
    consultationFee: 900,
    consultationType: "In-person & Online",
    chamberLocation: "Skin & Hair Clinic, Dhaka",
    about:
      "Dr. Nusrat Jahan is a renowned dermatologist known for her expertise in treating chronic skin conditions and hair loss. She combines medical and aesthetic approaches.",
    education: "MBBS from Chittagong Medical College; MD (Dermatology) from BSMMU",
    services: [
      "Hair Transplant Consultation",
      "Acne Treatment",
      "Psoriasis Management",
      "Anti-Aging Treatment",
    ],
    availableDays: ["Tuesday", "Thursday", "Sunday"],
  },
  {
    id: 16,
    name: "Dr. Kamal Uddin",
    image: "/images/doctors/doctor-4.png",
    speciality: "Orthopedic Surgeon",
    degree: "MBBS, MS (Orthopedics)",
    rating: 4.6,
    reviewCount: 38,
    experience: 10,
    consultationFee: 1200,
    consultationType: "In-person",
    chamberLocation: "Ortho Care Center, Dhaka",
    about:
      "Dr. Kamal Uddin is an orthopedic surgeon specializing in joint replacement and trauma surgery. He uses minimally invasive techniques for faster recovery.",
    education: "MBBS from Rajshahi Medical College; MS (Orthopedics) from BSMMU",
    services: [
      "Arthroscopic Surgery",
      "Joint Replacement",
      "Fracture Management",
      "Sports Injury Surgery",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 17,
    name: "Dr. Rina Akter",
    image: "/images/doctors/doctor-5.png",
    speciality: "Pediatrician",
    degree: "MBBS, DCH, FCPS (Pediatrics)",
    rating: 4.9,
    reviewCount: 62,
    experience: 14,
    consultationFee: 1000,
    consultationType: "Online & In-person",
    chamberLocation: "Children's Hospital, Dhaka",
    about:
      "Dr. Rina Akter is a highly respected pediatrician with a special interest in neonatal care and childhood immunization. She is known for her gentle approach with young patients.",
    education:
      "MBBS from Dhaka Medical College; DCH from IPGMER; FCPS (Pediatrics) from BCPS",
    services: [
      "Neonatal Care",
      "Child Vaccination",
      "Growth & Development Assessment",
      "Pediatric Emergency",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 18,
    name: "Dr. Imran Khan",
    image: "/images/doctors/doctor-6.png",
    speciality: "General Physician",
    degree: "MBBS, MD (Internal Medicine)",
    rating: 4.4,
    reviewCount: 27,
    experience: 6,
    consultationFee: 500,
    consultationType: "Online & In-person",
    chamberLocation: "Community Health Center, Dhaka",
    about:
      "Dr. Imran Khan is a general physician focused on providing accessible and comprehensive primary healthcare services to patients of all ages.",
    education: "MBBS from Sylhet MAG Osmani Medical College; MD (Internal Medicine) from BSMMU",
    services: [
      "General Health Checkup",
      "Fever & Infection Treatment",
      "Chronic Disease Management",
      "Health Counseling",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 19,
    name: "Dr. Ayesha Siddiqua",
    image: "/images/doctors/doctor-7.png",
    speciality: "Gynecologist",
    degree: "MBBS, FCPS (Gynecology & Obstetrics)",
    rating: 4.8,
    reviewCount: 47,
    experience: 12,
    consultationFee: 1100,
    consultationType: "In-person",
    chamberLocation: "Women's Care Hospital, Dhaka",
    about:
      "Dr. Ayesha Siddiqua is an expert in high-risk obstetrics and minimally invasive gynecological surgery. She is dedicated to women's health and wellness.",
    education:
      "MBBS from Chittagong Medical College; FCPS (Gynecology & Obstetrics) from BCPS",
    services: [
      "High-Risk Pregnancy Care",
      "Laparoscopic Hysterectomy",
      "PCOS Management",
      "Family Planning",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 20,
    name: "Dr. Mahbubur Rahman",
    image: "/images/doctors/doctor-8.png",
    speciality: "Ophthalmologist",
    degree: "MBBS, FCPS (Ophthalmology)",
    rating: 4.6,
    reviewCount: 31,
    experience: 9,
    consultationFee: 750,
    consultationType: "In-person & Online",
    chamberLocation: "Vision Care Center, Dhaka",
    about:
      "Dr. Mahbubur Rahman is an ophthalmologist specializing in corneal diseases and refractive surgery. He is committed to restoring and preserving vision.",
    education: "MBBS from Rajshahi Medical College; FCPS (Ophthalmology) from BCPS",
    services: [
      "Corneal Transplant",
      "Refractive Surgery",
      "Glaucoma Screening",
      "Cataract Surgery",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 21,
    name: "Dr. Tanzila Noor",
    image: "/images/doctors/doctor-9.png",
    speciality: "Psychiatrist",
    degree: "MBBS, MD (Psychiatry)",
    rating: 4.7,
    reviewCount: 44,
    experience: 8,
    consultationFee: 900,
    consultationType: "Online & In-person",
    chamberLocation: "MindCare Clinic, Dhaka",
    about:
      "Dr. Tanzila Noor is a psychiatrist specializing in adolescent mental health and mood disorders. She provides evidence-based treatments including CBT and medication management.",
    education: "MBBS from Dhaka Medical College; MD (Psychiatry) from BSMMU",
    services: [
      "Depression & Anxiety Treatment",
      "Adolescent Counseling",
      "Sleep Disorder Management",
      "Psychotherapy",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 22,
    name: "Dr. Shafiul Alam",
    image: "/images/doctors/doctor-10.png",
    speciality: "ENT Specialist",
    degree: "MBBS, FCPS (ENT), MS (ENT)",
    rating: 4.5,
    reviewCount: 22,
    experience: 7,
    consultationFee: 700,
    consultationType: "In-person",
    chamberLocation: "ENT & Head Neck Surgery Center, Dhaka",
    about:
      "Dr. Shafiul Alam is an ENT specialist with expertise in sinus surgery, head and neck oncology, and cochlear implants.",
    education: "MBBS from Mymensingh Medical College; FCPS (ENT) from BCPS; MS (ENT) from BSMMU",
    services: [
      "Functional Endoscopic Sinus Surgery",
      "Cochlear Implant Evaluation",
      "Tympanoplasty",
      "Head and Neck Cancer Screening",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 23,
    name: "Dr. Priya Das",
    image: "/images/doctors/doctor-11.png",
    speciality: "Endocrinologist",
    degree: "MBBS, MD (Endocrinology)",
    rating: 4.8,
    reviewCount: 40,
    experience: 10,
    consultationFee: 1100,
    consultationType: "In-person & Online",
    chamberLocation: "Endocrine Clinic, Dhaka",
    about:
      "Dr. Priya Das is an endocrinologist specializing in diabetes, thyroid, and adrenal disorders. She takes a holistic approach to hormonal health.",
    education: "MBBS from Chittagong Medical College; MD (Endocrinology) from BSMMU",
    services: [
      "Diabetes Care",
      "Thyroid Management",
      "Adrenal & Pituitary Disorders",
      "Osteoporosis Screening",
    ],
    availableDays: ["Sunday", "Tuesday", "Saturday"],
  },
  {
    id: 24,
    name: "Dr. Sajjad Hossain",
    image: "/images/doctors/doctor-12.png",
    speciality: "Gastroenterologist",
    degree: "MBBS, MD (Gastroenterology)",
    rating: 4.6,
    reviewCount: 35,
    experience: 9,
    consultationFee: 1200,
    consultationType: "In-person",
    chamberLocation: "Gastro & Liver Clinic, Dhaka",
    about:
      "Dr. Sajjad Hossain is a gastroenterologist with extensive experience in managing liver diseases, peptic ulcers, and IBS. He performs advanced endoscopic procedures.",
    education: "MBBS from Rajshahi Medical College; MD (Gastroenterology) from BSMMU",
    services: [
      "ERCP",
      "Liver Biopsy",
      "IBS Treatment",
      "Peptic Ulcer Management",
    ],
    availableDays: ["Monday", "Thursday", "Saturday"],
  },
  {
    id: 25,
    name: "Dr. Nahid Akter",
    image: "/images/doctors/doctor-1.png",
    speciality: "Pulmonologist",
    degree: "MBBS, MD (Pulmonology), FCCP",
    rating: 4.7,
    reviewCount: 29,
    experience: 8,
    consultationFee: 950,
    consultationType: "In-person & Online",
    chamberLocation: "Lung Care Center, Dhaka",
    about:
      "Dr. Nahid Akter is a pulmonologist specializing in asthma, COPD, and sleep disorders. She is dedicated to improving respiratory health.",
    education:
      "MBBS from Dhaka Medical College; MD (Pulmonology) from BSMMU; FCCP from American College of Chest Physicians",
    services: [
      "Asthma Management",
      "Sleep Study (Polysomnography)",
      "COPD Care",
      "Bronchoscopy",
    ],
    availableDays: ["Sunday", "Wednesday", "Friday"],
  },
  {
    id: 26,
    name: "Dr. Rezaul Karim",
    image: "/images/doctors/doctor-2.png",
    speciality: "Nephrologist",
    degree: "MBBS, MD (Nephrology), FRCP",
    rating: 4.8,
    reviewCount: 36,
    experience: 11,
    consultationFee: 1100,
    consultationType: "In-person",
    chamberLocation: "Kidney Hospital, Dhaka",
    about:
      "Dr. Rezaul Karim is a nephrologist with expertise in kidney transplantation, dialysis, and chronic kidney disease management.",
    education:
      "MBBS from Chittagong Medical College; MD (Nephrology) from BSMMU; FRCP from Royal College of Physicians",
    services: [
      "Hemodialysis",
      "Kidney Transplantation",
      "CKD Management",
      "Renal Biopsy",
    ],
    availableDays: ["Monday", "Thursday", "Saturday"],
  },
  {
    id: 27,
    name: "Dr. Munira Begum",
    image: "/images/doctors/doctor-3.png",
    speciality: "Urologist",
    degree: "MBBS, FCPS (Urology), FEBU",
    rating: 4.6,
    reviewCount: 25,
    experience: 8,
    consultationFee: 1000,
    consultationType: "In-person & Online",
    chamberLocation: "Urology & Nephrology Center, Dhaka",
    about:
      "Dr. Munira Begum is a urologist specializing in kidney stones, urinary tract infections, and female urology.",
    education:
      "MBBS from Rajshahi Medical College; FCPS (Urology) from BCPS; FEBU from European Board of Urology",
    services: [
      "PCNL & ESWL",
      "TURP",
      "Female Urology",
      "Male Infertility Treatment",
    ],
    availableDays: ["Tuesday", "Wednesday", "Friday"],
  },
  {
    id: 28,
    name: "Dr. Farhana Islam",
    image: "/images/doctors/doctor-4.png",
    speciality: "Oncologist",
    degree: "MBBS, MD (Clinical Oncology), FRCR",
    rating: 4.9,
    reviewCount: 41,
    experience: 13,
    consultationFee: 1400,
    consultationType: "In-person",
    chamberLocation: "National Cancer Institute, Dhaka",
    about:
      "Dr. Farhana Islam is a clinical oncologist specializing in breast cancer, chemotherapy, and radiation therapy. She is dedicated to compassionate cancer care.",
    education:
      "MBBS from Dhaka Medical College; MD (Clinical Oncology) from BSMMU; FRCR from Royal College of Radiologists",
    services: [
      "Chemotherapy",
      "Radiation Therapy",
      "Breast Cancer Treatment",
      "Palliative Care",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 29,
    name: "Dr. Ashraful Haque",
    image: "/images/doctors/doctor-5.png",
    speciality: "Hematologist",
    degree: "MBBS, MD (Hematology), FRCPath",
    rating: 4.7,
    reviewCount: 18,
    experience: 7,
    consultationFee: 1100,
    consultationType: "In-person",
    chamberLocation: "Hematology Center, Dhaka",
    about:
      "Dr. Ashraful Haque is a hematologist specializing in blood disorders, anemia, and clotting disorders. He provides expert diagnosis and treatment.",
    education:
      "MBBS from Mymensingh Medical College; MD (Hematology) from BSMMU; FRCPath from Royal College of Pathologists",
    services: [
      "Bone Marrow Biopsy",
      "Anemia Treatment",
      "Thalassemia Management",
      "Hemophilia Care",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 30,
    name: "Dr. Shirin Sultana",
    image: "/images/doctors/doctor-6.png",
    speciality: "Neonatologist",
    degree: "MBBS, FCPS (Pediatrics), MD (Neonatology)",
    rating: 4.9,
    reviewCount: 28,
    experience: 10,
    consultationFee: 1200,
    consultationType: "In-person",
    chamberLocation: "Neonatal Unit, Dhaka Medical College Hospital",
    about:
      "Dr. Shirin Sultana is a neonatologist dedicated to the care of premature and critically ill newborns. She has extensive experience in NICU management.",
    education:
      "MBBS from Dhaka Medical College; FCPS (Pediatrics) from BCPS; MD (Neonatology) from BSMMU",
    services: [
      "NICU Care",
      "Premature Baby Management",
      "Neonatal Screening",
      "Newborn Resuscitation",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 31,
    name: "Dr. Masud Rana",
    image: "/images/doctors/doctor-7.png",
    speciality: "Geriatrician",
    degree: "MBBS, MD (Geriatrics)",
    rating: 4.6,
    reviewCount: 14,
    experience: 9,
    consultationFee: 800,
    consultationType: "In-person & Online",
    chamberLocation: "Geriatric Care Clinic, Dhaka",
    about:
      "Dr. Masud Rana specializes in the healthcare needs of older adults, focusing on chronic disease management, mobility, and cognitive health.",
    education: "MBBS from Rajshahi Medical College; MD (Geriatrics) from BSMMU",
    services: [
      "Comprehensive Geriatric Assessment",
      "Fall Prevention Program",
      "Memory Clinic",
      "Polypharmacy Review",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 32,
    name: "Dr. Tareq Mahmud",
    image: "/images/doctors/doctor-8.png",
    speciality: "General Surgeon",
    degree: "MBBS, FCPS (Surgery), MS (Surgery)",
    rating: 4.7,
    reviewCount: 52,
    experience: 14,
    consultationFee: 1000,
    consultationType: "In-person",
    chamberLocation: "Surgery & Trauma Center, Dhaka",
    about:
      "Dr. Tareq Mahmud is a general surgeon with extensive experience in abdominal surgery, trauma care, and minimally invasive procedures.",
    education: "MBBS from Dhaka Medical College; FCPS (Surgery) from BCPS; MS (Surgery) from BSMMU",
    services: [
      "Laparoscopic Cholecystectomy",
      "Appendectomy",
      "Hernia Repair",
      "Trauma Surgery",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 33,
    name: "Dr. Liza Akter",
    image: "/images/doctors/doctor-9.png",
    speciality: "Plastic Surgeon",
    degree: "MBBS, FCPS (Plastic Surgery), FRCS",
    rating: 4.8,
    reviewCount: 34,
    experience: 11,
    consultationFee: 1800,
    consultationType: "In-person",
    chamberLocation: "Aesthetic Surgery Clinic, Dhaka",
    about:
      "Dr. Liza Akter is a plastic surgeon specializing in reconstructive surgery and cosmetic procedures. She is known for her artistic approach and patient-centered care.",
    education:
      "MBBS from Chittagong Medical College; FCPS (Plastic Surgery) from BCPS; FRCS from Royal College of Surgeons",
    services: [
      "Rhinoplasty",
      "Breast Augmentation",
      "Burn Reconstruction",
      "Body Contouring",
    ],
    availableDays: ["Sunday", "Wednesday", "Friday"],
  },
  {
    id: 34,
    name: "Dr. Saiful Islam",
    image: "/images/doctors/doctor-10.png",
    speciality: "ENT Specialist",
    degree: "MBBS, FCPS (ENT)",
    rating: 4.4,
    reviewCount: 20,
    experience: 6,
    consultationFee: 650,
    consultationType: "In-person & Online",
    chamberLocation: "ENT Clinic, Dhaka",
    about:
      "Dr. Saiful Islam is a young and dynamic ENT specialist focusing on sinus disorders, hearing impairments, and throat infections.",
    education: "MBBS from Mymensingh Medical College; FCPS (ENT) from BCPS",
    services: [
      "Sinus Treatment",
      "Hearing Aid Fitting",
      "Tonsillectomy",
      "Allergy Testing",
    ],
    availableDays: ["Monday", "Thursday", "Saturday"],
  },
  {
    id: 35,
    name: "Dr. Rahim Uddin",
    image: "/images/doctors/doctor-11.png",
    speciality: "Dentist",
    degree: "BDS, MDS (Oral & Maxillofacial Surgery)",
    rating: 4.7,
    reviewCount: 48,
    experience: 10,
    consultationFee: 700,
    consultationType: "In-person",
    chamberLocation: "Smile Dental Clinic, Dhaka",
    about:
      "Dr. Rahim Uddin is a dentist specializing in oral surgery and implantology. He provides comprehensive dental care from routine checkups to complex surgeries.",
    education: "BDS from Dhaka Dental College; MDS (Oral & Maxillofacial Surgery) from BSMMU",
    services: [
      "Dental Implants",
      "Root Canal Treatment",
      "Wisdom Tooth Extraction",
      "Teeth Whitening",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 36,
    name: "Dr. Shahnaz Parvin",
    image: "/images/doctors/doctor-12.png",
    speciality: "Anesthesiologist",
    degree: "MBBS, DA, FCPS (Anesthesiology)",
    rating: 4.8,
    reviewCount: 15,
    experience: 9,
    consultationFee: 800,
    consultationType: "In-person",
    chamberLocation: "Anesthesia & Pain Management Clinic, Dhaka",
    about:
      "Dr. Shahnaz Parvin is an anesthesiologist specializing in pain management and perioperative anesthesia. She ensures patient safety during surgical procedures.",
    education:
      "MBBS from Rajshahi Medical College; DA from IPGMER; FCPS (Anesthesiology) from BCPS",
    services: [
      "General Anesthesia",
      "Epidural & Spinal Anesthesia",
      "Chronic Pain Management",
      "Pre-Anesthetic Checkup",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 37,
    name: "Dr. Kamrul Hasan",
    image: "/images/doctors/doctor-1.png",
    speciality: "Allergist & Immunologist",
    degree: "MBBS, MD (Allergy & Immunology)",
    rating: 4.5,
    reviewCount: 12,
    experience: 6,
    consultationFee: 900,
    consultationType: "Online & In-person",
    chamberLocation: "Allergy & Asthma Clinic, Dhaka",
    about:
      "Dr. Kamrul Hasan is an allergist and immunologist specializing in allergy testing, asthma management, and immune disorders.",
    education: "MBBS from Chittagong Medical College; MD (Allergy & Immunology) from BSMMU",
    services: [
      "Allergy Testing",
      "Asthma Management",
      "Immunotherapy",
      "Food Allergy Diagnosis",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 38,
    name: "Dr. Sanjida Akter",
    image: "/images/doctors/doctor-2.png",
    speciality: "Radiologist",
    degree: "MBBS, MD (Radiology), FRCR",
    rating: 4.6,
    reviewCount: 23,
    experience: 8,
    consultationFee: 1000,
    consultationType: "In-person",
    chamberLocation: "Diagnostic Imaging Center, Dhaka",
    about:
      "Dr. Sanjida Akter is a radiologist specializing in MRI, CT, and ultrasound diagnostics. She provides accurate and timely radiological interpretations.",
    education:
      "MBBS from Dhaka Medical College; MD (Radiology) from BSMMU; FRCR from Royal College of Radiologists",
    services: [
      "MRI Scan",
      "CT Scan",
      "Ultrasound",
      "Mammography",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 39,
    name: "Dr. Mehedi Hasan",
    image: "/images/doctors/doctor-3.png",
    speciality: "Physiotherapist",
    degree: "BPT, MPT (Orthopedic Physiotherapy)",
    rating: 4.7,
    reviewCount: 37,
    experience: 9,
    consultationFee: 600,
    consultationType: "In-person & Online",
    chamberLocation: "PhysioCare Center, Dhaka",
    about:
      "Dr. Mehedi Hasan is a physiotherapist specializing in orthopedic and neurological rehabilitation. He helps patients recover from injuries and surgeries.",
    education: "BPT from Bangladesh Institute of Health Sciences; MPT (Orthopedic) from University of Dhaka",
    services: [
      "Manual Therapy",
      "Therapeutic Exercises",
      "Electrotherapy",
      "Post-Surgery Rehabilitation",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 40,
    name: "Dr. Nasreen Sultana",
    image: "/images/doctors/doctor-4.png",
    speciality: "Nutritionist & Dietitian",
    degree: "BSc (Nutrition & Food Science), MSc (Clinical Nutrition)",
    rating: 4.8,
    reviewCount: 44,
    experience: 10,
    consultationFee: 700,
    consultationType: "Online & In-person",
    chamberLocation: "Nutrition & Wellness Clinic, Dhaka",
    about:
      "Dr. Nasreen Sultana is a clinical nutritionist helping patients achieve their health goals through personalized diet plans and nutritional counseling.",
    education:
      "BSc from University of Dhaka; MSc (Clinical Nutrition) from University of Aberdeen",
    services: [
      "Weight Management",
      "Diabetes Diet Planning",
      "Sports Nutrition",
      "Prenatal Nutrition",
    ],
    availableDays: ["Sunday", "Tuesday", "Friday"],
  },
  {
    id: 41,
    name: "Dr. Anisur Rahman",
    image: "/images/doctors/doctor-5.png",
    speciality: "General Surgeon",
    degree: "MBBS, FCPS (Surgery)",
    rating: 4.5,
    reviewCount: 30,
    experience: 8,
    consultationFee: 900,
    consultationType: "In-person",
    chamberLocation: "City Hospital, Dhaka",
    about:
      "Dr. Anisur Rahman is a general surgeon with expertise in laparoscopic procedures and emergency surgery. He has performed over 3,000 successful surgeries.",
    education: "MBBS from Chittagong Medical College; FCPS (Surgery) from BCPS",
    services: [
      "Laparoscopic Surgery",
      "Emergency Surgery",
      "Gallbladder Surgery",
      "Varicose Vein Surgery",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 42,
    name: "Dr. Farzana Akter",
    image: "/images/doctors/doctor-6.png",
    speciality: "Obstetrician & Gynecologist",
    degree: "MBBS, FCPS (Obstetrics & Gynecology)",
    rating: 4.9,
    reviewCount: 55,
    experience: 15,
    consultationFee: 1300,
    consultationType: "In-person",
    chamberLocation: "Mother & Child Hospital, Dhaka",
    about:
      "Dr. Farzana Akter is an obstetrician and gynecologist with extensive experience in high-risk pregnancies and gynecological oncology.",
    education:
      "MBBS from Dhaka Medical College; FCPS (Obstetrics & Gynecology) from BCPS",
    services: [
      "High-Risk Obstetrics",
      "Cesarean Section",
      "Gynecologic Oncology",
      "Fertility Treatment",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 43,
    name: "Dr. Shahidul Islam",
    image: "/images/doctors/doctor-7.png",
    speciality: "Cardiologist",
    degree: "MBBS, MD (Cardiology), FESC",
    rating: 4.6,
    reviewCount: 27,
    experience: 9,
    consultationFee: 1100,
    consultationType: "In-person & Online",
    chamberLocation: "Heart Foundation Hospital, Dhaka",
    about:
      "Dr. Shahidul Islam is a cardiologist specializing in interventional cardiology and electrophysiology. He has performed over 2,000 cardiac catheterizations.",
    education:
      "MBBS from Rajshahi Medical College; MD (Cardiology) from BSMMU; FESC from European Society of Cardiology",
    services: [
      "Cardiac Catheterization",
      "Pacemaker Implantation",
      "Electrophysiology Study",
      "Coronary Angioplasty",
    ],
    availableDays: ["Sunday", "Wednesday", "Friday"],
  },
  {
    id: 44,
    name: "Dr. Nazrul Islam",
    image: "/images/doctors/doctor-8.png",
    speciality: "General Physician",
    degree: "MBBS, MD (Internal Medicine)",
    rating: 4.5,
    reviewCount: 22,
    experience: 7,
    consultationFee: 600,
    consultationType: "Online",
    chamberLocation: "Telemedicine Platform, Dhaka",
    about:
      "Dr. Nazrul Islam provides online general medical consultations, focusing on preventive care and chronic disease management. He offers convenient telemedicine services.",
    education: "MBBS from Sylhet MAG Osmani Medical College; MD (Internal Medicine) from BSMMU",
    services: [
      "Online Consultation",
      "Prescription Refill",
      "Health Advice",
      "Lab Test Interpretation",
    ],
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  },
  {
    id: 45,
    name: "Dr. Jannatul Ferdous",
    image: "/images/doctors/doctor-9.png",
    speciality: "Dermatologist",
    degree: "MBBS, DDVL",
    rating: 4.7,
    reviewCount: 38,
    experience: 8,
    consultationFee: 850,
    consultationType: "Online & In-person",
    chamberLocation: "Derma Skin Clinic, Dhaka",
    about:
      "Dr. Jannatul Ferdous is a dermatologist specializing in cosmetic dermatology and skin rejuvenation. She offers advanced laser and injectable treatments.",
    education: "MBBS from Dhaka Medical College; DDVL from IPGMER",
    services: [
      "Botox & Fillers",
      "Chemical Peels",
      "Laser Hair Removal",
      "Acne Scar Treatment",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 46,
    name: "Dr. Mizanur Rahman",
    image: "/images/doctors/doctor-10.png",
    speciality: "Orthopedic Surgeon",
    degree: "MBBS, MS (Orthopedics), FAB",
    rating: 4.8,
    reviewCount: 45,
    experience: 12,
    consultationFee: 1400,
    consultationType: "In-person",
    chamberLocation: "Ortho & Spine Hospital, Dhaka",
    about:
      "Dr. Mizanur Rahman is an orthopedic surgeon specializing in spine surgery and complex trauma. He uses advanced navigation techniques for precision.",
    education:
      "MBBS from Chittagong Medical College; MS (Orthopedics) from BSMMU; FAB from Bangladesh Orthopaedic Association",
    services: [
      "Spine Surgery",
      "Microdiscectomy",
      "Complex Fracture Fixation",
      "Spine Deformity Correction",
    ],
    availableDays: ["Monday", "Wednesday", "Saturday"],
  },
  {
    id: 47,
    name: "Dr. Sharmin Akter",
    image: "/images/doctors/doctor-11.png",
    speciality: "Pediatrician",
    degree: "MBBS, FCPS (Pediatrics)",
    rating: 4.6,
    reviewCount: 30,
    experience: 8,
    consultationFee: 800,
    consultationType: "Online & In-person",
    chamberLocation: "Happy Kids Clinic, Dhaka",
    about:
      "Dr. Sharmin Akter is a pediatrician specializing in childhood allergies and asthma. She provides comprehensive care for children with chronic conditions.",
    education: "MBBS from Rajshahi Medical College; FCPS (Pediatrics) from BCPS",
    services: [
      "Childhood Asthma Management",
      "Allergy Testing",
      "Developmental Screening",
      "Nutritional Guidance",
    ],
    availableDays: ["Sunday", "Tuesday", "Thursday"],
  },
  {
    id: 48,
    name: "Dr. Zakir Hossain",
    image: "/images/doctors/doctor-12.png",
    speciality: "Gastroenterologist",
    degree: "MBBS, MD (Gastroenterology)",
    rating: 4.5,
    reviewCount: 19,
    experience: 7,
    consultationFee: 1000,
    consultationType: "In-person",
    chamberLocation: "Digestive Health Clinic, Dhaka",
    about:
      "Dr. Zakir Hossain is a gastroenterologist with a focus on liver diseases and endoscopy. He is committed to providing quality digestive health care.",
    education: "MBBS from Mymensingh Medical College; MD (Gastroenterology) from BSMMU",
    services: [
      "Liver Function Management",
      "Endoscopy",
      "Colonoscopy",
      "Pancreatic Disorder Treatment",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: 49,
    name: "Dr. Afsana Begum",
    image: "/images/doctors/doctor-1.png",
    speciality: "Gynecologist",
    degree: "MBBS, FCPS (Gynecology & Obstetrics)",
    rating: 4.7,
    reviewCount: 35,
    experience: 10,
    consultationFee: 1000,
    consultationType: "In-person & Online",
    chamberLocation: "Women's Wellness Clinic, Dhaka",
    about:
      "Dr. Afsana Begum is a gynecologist specializing in adolescent gynecology and reproductive health. She provides compassionate care for women of all ages.",
    education: "MBBS from Dhaka Medical College; FCPS (Gynecology & Obstetrics) from BCPS",
    services: [
      "Adolescent Gynecology",
      "Reproductive Health",
      "Menstrual Disorder Treatment",
      "Contraception Counseling",
    ],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
  },
  {
    id: 50,
    name: "Dr. Mostafa Kamal",
    image: "/images/doctors/doctor-2.png",
    speciality: "Neurologist",
    degree: "MBBS, MD (Neurology)",
    rating: 4.8,
    reviewCount: 40,
    experience: 11,
    consultationFee: 1100,
    consultationType: "In-person",
    chamberLocation: "Neuro Care Center, Dhaka",
    about:
      "Dr. Mostafa Kamal is a neurologist specializing in epilepsy surgery and neurocritical care. He is at the forefront of neurological treatments in Bangladesh.",
    education: "MBBS from Chittagong Medical College; MD (Neurology) from BSMMU",
    services: [
      "Epilepsy Surgery Consultation",
      "Neurocritical Care",
      "Stroke Management",
      "Neuroimaging Interpretation",
    ],
    availableDays: ["Sunday", "Wednesday", "Friday"],
  },
];

export default doctors;
