const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Ahmed",
    image: "/images/doctors/doctor-1.png",
    speciality: "Cardiologist",
    rating: 4.9,
    reviewCount: 45,
    experience: 12,
    consultationFee: 1200,
  },
  {
    id: 2,
    name: "Dr. Michael Rahman",
    image: "/images/doctors/doctor-2.png",
    speciality: "Neurologist",
    rating: 4.8,
    reviewCount: 21,
    experience: 10,
    consultationFee: 1000,
  },
  {
    id: 3,
    name: "Dr. Emily Wilson",
    image: "/images/doctors/doctor-3.png",
    speciality: "Dermatologist",
    rating: 4.7,
    reviewCount: 16,
    experience: 8,
    consultationFee: 800,
  },
  {
    id: 4,
    name: "Dr. James Anderson",
    image: "/images/doctors/doctor-4.png",
    speciality: "Orthopedic Surgeon",
    rating: 4.9,
    reviewCount: 71,
    experience: 15,
    consultationFee: 1500,
  },
  {
    id: 5,
    name: "Dr. Olivia Martin",
    image: "/images/doctors/doctor-5.png",
    speciality: "Pediatrician",
    rating: 4.8,
    reviewCount: 24,
    experience: 9,
    consultationFee: 900,
  },
  {
    id: 6,
    name: "Dr. Daniel Karim",
    image: "/images/doctors/doctor-6.png",
    speciality: "General Physician",
    rating: 4.6,
    reviewCount: 29,
    experience: 7,
    consultationFee: 600,
  },
  {
    id: 7,
    name: "Dr. Sophia Williams",
    image: "/images/doctors/doctor-7.png",
    speciality: "Gynecologist",
    rating: 4.9,
    reviewCount: 42,
    experience: 13,
    consultationFee: 1100,
  },
  {
    id: 8,
    name: "Dr. Robert Hasan",
    image: "/images/doctors/doctor-8.png",
    speciality: "Ophthalmologist",
    rating: 4.7,
    reviewCount: 39,
    experience: 11,
    consultationFee: 850,
  },
  {
    id: 9,
    name: "Dr. Isabella Khan",
    image: "/images/doctors/doctor-9.png",
    speciality: "Psychiatrist",
    rating: 4.8,
    reviewCount: 67,
    experience: 10,
    consultationFee: 1000,
  },
  {
    id: 10,
    name: "Dr. William Chowdhury",
    image: "/images/doctors/doctor-10.png",
    speciality: "ENT Specialist",
    rating: 4.6,
    reviewCount: 54,
    experience: 8,
    consultationFee: 750,
  },
  {
    id: 11,
    name: "Dr. Emma Hossain",
    image: "/images/doctors/doctor-11.png",
    speciality: "Endocrinologist",
    rating: 4.9,
    reviewCount: 51,
    experience: 14,
    consultationFee: 1200,
  },
  {
    id: 12,
    name: "Dr. Alexander Islam",
    image: "/images/doctors/doctor-12.png",
    speciality: "Gastroenterologist",
    rating: 4.8,
    reviewCount: 88,
    experience: 12,
    consultationFee: 1300,
  },
];

export default doctors;
