import {
  LuAccessibility,
  LuActivity,
  LuApple,
  LuBaby,
  LuBone,
  LuBrain,
  LuCircleDot,
  LuDroplet,
  LuDroplets,
  LuEar,
  LuEye,
  LuHeart,
  LuHeartPulse,
  LuPersonStanding,
  LuPill,
  LuRibbon,
  LuScan,
  LuScissors,
  LuSmile,
  LuSparkles,
  LuStethoscope,
  LuSyringe,
  LuWind,
} from "react-icons/lu";
import { FaLungs, FaTooth } from "react-icons/fa";

const specialityColors = {
  red: {
    bg: "#FEE2E2",
    text: "#EF4444",
    border: "#FECACA",
    bgClass: "bg-red-100",
    textClass: "text-red-500",
    borderClass: "border-red-200",
    hoverBgClass: "hover:bg-red-100",
  },
  blue: {
    bg: "#DBEAFE",
    text: "#3B82F6",
    border: "#BFDBFE",
    bgClass: "bg-blue-100",
    textClass: "text-blue-500",
    borderClass: "border-blue-200",
    hoverBgClass: "hover:bg-blue-100",
  },
  purple: {
    bg: "#EDE9FE",
    text: "#8B5CF6",
    border: "#DDD6FE",
    bgClass: "bg-purple-100",
    textClass: "text-purple-500",
    borderClass: "border-purple-200",
    hoverBgClass: "hover:bg-purple-100",
  },
  pink: {
    bg: "#FCE7F3",
    text: "#EC4899",
    border: "#FBCFE8",
    bgClass: "bg-pink-100",
    textClass: "text-pink-500",
    borderClass: "border-pink-200",
    hoverBgClass: "hover:bg-pink-100",
  },
  teal: {
    bg: "#CCFBF1",
    text: "#14B8A6",
    border: "#99F6E4",
    bgClass: "bg-teal-100",
    textClass: "text-teal-500",
    borderClass: "border-teal-200",
    hoverBgClass: "hover:bg-teal-100",
  },
  green: {
    bg: "#DCFCE7",
    text: "#22C55E",
    border: "#BBF7D0",
    bgClass: "bg-green-100",
    textClass: "text-green-500",
    borderClass: "border-green-200",
    hoverBgClass: "hover:bg-green-100",
  },
  indigo: {
    bg: "#E0E7FF",
    text: "#6366F1",
    border: "#C7D2FE",
    bgClass: "bg-indigo-100",
    textClass: "text-indigo-500",
    borderClass: "border-indigo-200",
    hoverBgClass: "hover:bg-indigo-100",
  },
  orange: {
    bg: "#FFEDD5",
    text: "#F97316",
    border: "#FED7AA",
    bgClass: "bg-orange-100",
    textClass: "text-orange-500",
    borderClass: "border-orange-200",
    hoverBgClass: "hover:bg-orange-100",
  },
  rose: {
    bg: "#FFE4E6",
    text: "#F43F5E",
    border: "#FECDD3",
    bgClass: "bg-rose-100",
    textClass: "text-rose-500",
    borderClass: "border-rose-200",
    hoverBgClass: "hover:bg-rose-100",
  },
  amber: {
    bg: "#FEF3C7",
    text: "#F59E0B",
    border: "#FDE68A",
    bgClass: "bg-amber-100",
    textClass: "text-amber-500",
    borderClass: "border-amber-200",
    hoverBgClass: "hover:bg-amber-100",
  },
  cyan: {
    bg: "#CFFAFE",
    text: "#06B6D4",
    border: "#A5F3FC",
    bgClass: "bg-cyan-100",
    textClass: "text-cyan-500",
    borderClass: "border-cyan-200",
    hoverBgClass: "hover:bg-cyan-100",
  },
  sky: {
    bg: "#E0F2FE",
    text: "#0EA5E9",
    border: "#BAE6FD",
    bgClass: "bg-sky-100",
    textClass: "text-sky-500",
    borderClass: "border-sky-200",
    hoverBgClass: "hover:bg-sky-100",
  },
  slate: {
    bg: "#F1F5F9",
    text: "#64748B",
    border: "#E2E8F0",
    bgClass: "bg-slate-100",
    textClass: "text-slate-500",
    borderClass: "border-slate-200",
    hoverBgClass: "hover:bg-slate-100",
  },
  fuchsia: {
    bg: "#FAE8FF",
    text: "#D946EF",
    border: "#F5D0FE",
    bgClass: "bg-fuchsia-100",
    textClass: "text-fuchsia-500",
    borderClass: "border-fuchsia-200",
    hoverBgClass: "hover:bg-fuchsia-100",
  },
};

const specialities = [
  {
    Icon: LuHeartPulse,
    name: "Cardiology",
    details: "Heart and cardiovascular care",
    color: specialityColors.red,
  },
  {
    Icon: LuBone,
    name: "Orthopedics",
    details: "Bone, muscle and joint care",
    color: specialityColors.blue,
  },
  {
    Icon: LuBrain,
    name: "Neurology",
    details: "Brain and nervous system",
    color: specialityColors.purple,
  },
  {
    Icon: LuBaby,
    name: "Pediatrics",
    details: "Healthcare for children",
    color: specialityColors.pink,
  },
  {
    Icon: LuEye,
    name: "Ophthalmology",
    details: "Complete eye care",
    color: specialityColors.teal,
  },
  {
    Icon: LuStethoscope,
    name: "General Medicine",
    details: "Primary healthcare",
    color: specialityColors.green,
  },
  {
    Icon: LuScan,
    name: "Radiology",
    details: "Medical imaging and diagnostics",
    color: specialityColors.indigo,
  },
  {
    Icon: LuPill,
    name: "Dermatology",
    details: "Skin, hair and nail care",
    color: specialityColors.orange,
  },
  {
    Icon: LuHeartPulse,
    name: "Psychology",
    details: "Mental and behavioral health",
    color: specialityColors.rose,
  },
  {
    Icon: LuActivity,
    name: "Gastroenterology",
    details: "Digestive system care",
    color: specialityColors.amber,
  },
  {
    Icon: FaLungs,
    name: "Pulmonology",
    details: "Lung and respiratory care",
    color: specialityColors.cyan,
  },
  {
    Icon: LuDroplets,
    name: "Nephrology",
    details: "Kidney health specialists",
    color: specialityColors.sky,
  },
  {
    Icon: LuCircleDot,
    name: "Urology",
    details: "Urinary and reproductive health",
    color: {
      ...specialityColors.blue,
      text: "#2563EB",
      textClass: "text-blue-600",
    },
  },
  {
    Icon: LuActivity,
    name: "Endocrinology",
    details: "Hormones and metabolism",
    color: {
      bg: "#FEF9C3",
      text: "#EAB308",
      border: "#FDE047",
      bgClass: "bg-yellow-100",
      textClass: "text-yellow-500",
      borderClass: "border-yellow-300",
      hoverBgClass: "hover:bg-yellow-100",
    },
  },
  {
    Icon: LuRibbon,
    name: "Oncology",
    details: "Cancer diagnosis and treatment",
    color: {
      ...specialityColors.pink,
      text: "#DB2777",
      textClass: "text-pink-600",
    },
  },
  {
    Icon: LuDroplet,
    name: "Hematology",
    details: "Blood and blood disorders",
    color: {
      ...specialityColors.red,
      text: "#DC2626",
      textClass: "text-red-600",
    },
  },
  {
    Icon: LuBaby,
    name: "Neonatology",
    details: "Care for newborn babies",
    color: {
      ...specialityColors.sky,
      text: "#38BDF8",
      textClass: "text-sky-400",
    },
  },
  {
    Icon: LuAccessibility,
    name: "Geriatrics",
    details: "Healthcare for older adults",
    color: specialityColors.slate,
  },
  {
    Icon: LuScissors,
    name: "General Surgery",
    details: "Surgical treatment and care",
    color: specialityColors.red,
  },
  {
    Icon: LuSparkles,
    name: "Plastic Surgery",
    details: "Reconstructive and cosmetic surgery",
    color: specialityColors.fuchsia,
  },
  {
    Icon: LuEar,
    name: "ENT",
    details: "Ear, nose and throat care",
    color: {
      ...specialityColors.teal,
      text: "#0D9488",
      textClass: "text-teal-600",
    },
  },
  {
    Icon: LuSmile,
    name: "Dentistry",
    details: "Oral and dental healthcare",
    color: {
      ...specialityColors.cyan,
      text: "#0891B2",
      textClass: "text-cyan-600",
    },
  },
  {
    Icon: FaTooth,
    name: "Oral Surgery",
    details: "Surgical dental care",
    color: specialityColors.blue,
  },
  {
    Icon: LuSyringe,
    name: "Anesthesiology",
    details: "Anesthesia and pain management",
    color: specialityColors.purple,
  },
  {
    Icon: LuWind,
    name: "Allergy & Immunology",
    details: "Allergies and immune disorders",
    color: specialityColors.cyan,
  },
  {
    Icon: LuPersonStanding,
    name: "Physical Medicine",
    details: "Rehabilitation and recovery",
    color: specialityColors.orange,
  },
  {
    Icon: LuApple,
    name: "Nutrition & Dietetics",
    details: "Nutrition and healthy lifestyle",
    color: specialityColors.green,
  },
  {
    Icon: LuAccessibility,
    name: "Physiotherapy",
    details: "Movement and physical rehabilitation",
    color: specialityColors.teal,
  },
  {
    Icon: LuHeart,
    name: "Obstetrics & Gynecology",
    details: "Complete women's healthcare",
    color: {
      ...specialityColors.pink,
      text: "#DB2777",
      textClass: "text-pink-600",
    },
  },
  {
    Icon: LuBaby,
    name: "Pediatric",
    details: "Care for children",
    color: {
      ...specialityColors.orange,
      text: "#FB923C",
      textClass: "text-orange-400",
    },
  },
  {
    Icon: LuSmile,
    name: "Pediatric Dentistry",
    details: "Dental care for children",
    color: {
      ...specialityColors.cyan,
      text: "#22D3EE",
      textClass: "text-cyan-400",
    },
  },
];

export default specialities;
