const specialities = [
  {
    icon: "LuHeartPulse",
    name: "Cardiology",
    details: "Heart and cardiovascular care",
    color: "red-500",
  },
  {
    icon: "LuBone",
    name: "Orthopedics",
    details: "Bone, muscle and joint care",
    color: "blue-500",
  },
  {
    icon: "LuBrain",
    name: "Neurology",
    details: "Brain and nervous system",
    color: "purple-500",
  },
  {
    icon: "LuBaby",
    name: "Pediatrics",
    details: "Healthcare for children",
    color: "pink-500",
  },
  {
    icon: "LuEye",
    name: "Ophthalmology",
    details: "Complete eye care",
    color: "teal-500",
  },
  {
    icon: "LuStethoscope",
    name: "General Medicine",
    details: "Primary healthcare",
    color: "green-500",
  },
  {
    icon: "LuScan",
    name: "Radiology",
    details: "Medical imaging and diagnostics",
    color: "indigo-500",
  },
  {
    icon: "LuPill",
    name: "Dermatology",
    details: "Skin, hair and nail care",
    color: "orange-500",
  },
  {
    icon: "LuHeartPulse",
    name: "Psychology",
    details: "Mental and behavioral health",
    color: "rose-500",
  },
  {
    icon: "LuActivity",
    name: "Gastroenterology",
    details: "Digestive system care",
    color: "amber-500",
  },
  {
    icon: "LuLungs",
    name: "Pulmonology",
    details: "Lung and respiratory care",
    color: "cyan-500",
  },
  {
    icon: "LuDroplets",
    name: "Nephrology",
    details: "Kidney health specialists",
    color: "sky-500",
  },
  {
    icon: "LuCircleDot",
    name: "Urology",
    details: "Urinary and reproductive health",
    color: "blue-600",
  },
  {
    icon: "LuActivity",
    name: "Endocrinology",
    details: "Hormones and metabolism",
    color: "yellow-500",
  },
  {
    icon: "LuRibbon",
    name: "Oncology",
    details: "Cancer diagnosis and treatment",
    color: "pink-600",
  },
  {
    icon: "LuDroplet",
    name: "Hematology",
    details: "Blood and blood disorders",
    color: "red-600",
  },
  {
    icon: "LuBaby",
    name: "Neonatology",
    details: "Care for newborn babies",
    color: "sky-400",
  },
  {
    icon: "LuAccessibility",
    name: "Geriatrics",
    details: "Healthcare for older adults",
    color: "slate-500",
  },
  {
    icon: "LuScissors",
    name: "General Surgery",
    details: "Surgical treatment and care",
    color: "red-500",
  },
  {
    icon: "LuSparkles",
    name: "Plastic Surgery",
    details: "Reconstructive and cosmetic surgery",
    color: "fuchsia-500",
  },
  {
    icon: "LuEar",
    name: "ENT",
    details: "Ear, nose and throat care",
    color: "teal-600",
  },
  {
    icon: "LuSmile",
    name: "Dentistry",
    details: "Oral and dental healthcare",
    color: "cyan-600",
  },
  {
    icon: "LuTooth",
    name: "Oral Surgery",
    details: "Surgical dental care",
    color: "blue-500",
  },
  {
    icon: "LuSyringe",
    name: "Anesthesiology",
    details: "Anesthesia and pain management",
    color: "purple-500",
  },
  {
    icon: "LuWind",
    name: "Allergy & Immunology",
    details: "Allergies and immune disorders",
    color: "cyan-500",
  },
  {
    icon: "LuPersonStanding",
    name: "Physical Medicine",
    details: "Rehabilitation and recovery",
    color: "orange-500",
  },
  {
    icon: "LuApple",
    name: "Nutrition & Dietetics",
    details: "Nutrition and healthy lifestyle",
    color: "green-500",
  },
  {
    icon: "LuAccessibility",
    name: "Physiotherapy",
    details: "Movement and physical rehabilitation",
    color: "teal-500",
  },
  {
    icon: "LuHeart",
    name: "Obstetrics & Gynecology",
    details: "Complete women's healthcare",
    color: "pink-600",
  },
  {
    icon: "LuBaby",
    name: "Pediatric",
    details: "Care for children",
    color: "orange-400",
  },
  {
    icon: "LuSmile",
    name: "Pediatric Dentistry",
    details: "Dental care for children",
    color: "cyan-400",
  },
];

export default specialities;
